### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by lihaksa**

### CODE REVIEW

**Comment by Sparragus** [comment]
Hi @lihaksa 
I noticed you left me a message on Twitter, but it seems you figured out how to change the channel the bot connects to. Nice!

However, a pull request is not the correct solution. You should try forking this project, and then editing your own repository. After commiting and pushing to your repo, you should be able to use the Deploy button.

If you need any help forking and editing the code, let me know and I'll gladly help.

**Comment by lihaksa** [comment]
Hello Richard,

I am no coder by any means! I am actually a lawyer trying to sort out
something for our firm's team on Slack.

Thanks for all your help. Could you just tell me how to "commit and push to
my repo"?

Thank you so much,

_Melih AKSAN__Avukat / Attorney at Law, LLM_

Konaklar Mah. Akağaç Sk. Aksan Binası
No:7 34330 4.Levent - Beşiktaş / İstanbul

T +90 212 249 83 83
F +90 212 249 83 17
melih.aksan@aksan.av.tr
www.aksan.av.tr

Bu e-postanın tabi olduğu hükümler için lütfen
http://www.aksan.av.tr/hukukiuyari.html adresini ziyaret ediniz.
For details of the terms under which this email is distributed please go to
http://www.aksan.av.tr/legalnotice.html.

2015-11-23 17:55 GMT+02:00 Richard B. Kaufman-López <
notifications@github.com>:

**Comment by lihaksa** [comment]
Hello again,

I deployed my own master branch on Heroku but for some reason it does not
work. The slack bot does not post to the channel I want it to post (namely
"ikomitesidinliyor"). You know that I changed the relevant field in the
respective app.js document.

:( Thanks so much for help.

_Melih AKSAN__Avukat / Attorney at Law, LLM_

Konaklar Mah. Akağaç Sk. Aksan Binası
No:7 34330 4.Levent - Beşiktaş / İstanbul

T +90 212 249 83 83
F +90 212 249 83 17
melih.aksan@aksan.av.tr
www.aksan.av.tr

Bu e-postanın tabi olduğu hükümler için lütfen
http://www.aksan.av.tr/hukukiuyari.html adresini ziyaret ediniz.
For details of the terms under which this email is distributed please go to
http://www.aksan.av.tr/legalnotice.html.

2015-11-23 19:30 GMT+02:00 Melih Aksan melih.aksan@aksan.av.tr:

**Comment by Sparragus** [comment]
Try using this link to deploy your app: https://heroku.com/deploy?template=https://github.com/lihaksa/slack-bot-edward-snowden/tree/master

**Pull request closed without merging**
